### ISSUE TITLE
JSON HTTP API

### ISSUE THREAD

**Issue by bouncepaw** [bouncepaw/mycorrhiza#104]
Currently, Mycorrhiza does not have an API designed for machines. Most routes are meant to be requested by humans through browsers. Even though we can make third-party programs request them, they still cannot get all of the information they may need, so we need an API.

An example of a route designed for machines: https://mycorrhiza.wiki/title-search-json/?q=u

Why JSON? Because this format is:
1. Simple enough to put up with
2. The most popular format for this task in the industry
3. Already used in Mycorrhiza

So, no GraphQL nor XML. No home-brew serialization format (even though the idea is compelling).

A schema might be good too: https://json-schema.org

How do we make it good? Dunno, never done that.

Here are the routes I want to provide for the API:
* `/mycorrhiza` tells what version of Mycorrhiza used and stuff like that.
* All of human-oriented routes should be copied. Any exceptions?

I've seen many services include API version in the route. I don't want to do this.

By the way, such an API will make alternative front-ends possible. Cool.

**Comment by chekoopa** [comment]
> not sure why would anyone prefer simple REST APIs.

Because it is

> simple 

as you may generate the output without any dependencies, and it would work.

**Comment by handlerug** [comment]
> as you may generate the output without any dependencies, and it would work.

What do you mean "without dependencies"? What dependencies do you need to make a single POST request?

**Comment by bouncepaw** [comment]
Just to note, I've dropped both -json URLs some time ago

**Comment by bouncepaw** [comment]
Unclear. Maybe add something about Betula and ActivityPub. There's no real issue yet, so closing for now.
