### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by bouncepaw** [bouncepaw/mycorrhiza#109]
Currently, out logging is a mess.

We want to clean up this mess.

How?

**Comment by bouncepaw** [comment]
The question has been asked:

> Do we need structured logging?

To which I say: we don't really.

**Comment by bouncepaw** [comment]
A recent code scan has revealed a vulnerability in the logging system. 12 vulnerabilities, in fact. GitHub has notified about it.

<img width="626" alt="Снимок экрана 2021-12-15 в 21 12 31" src="https://user-images.githubusercontent.com/22562024/146242078-5800be8f-b7d5-466c-b592-6e5fe7fadfd5.png">

Yep, thanks a lot.

I guess we should do something about it. On the other hand, why

🌾

**Comment by handlerug** [comment]
https://github.com/golang/go/discussions/54763

**Comment by bouncepaw** [comment]
Since 2022, `slog` started existing. That's what ought to be used one day.

**Comment by bouncepaw** [comment]
In an two-hour rush, implemented. I like it!
