### ISSUE TITLE
Link full diff in recent changes

### ISSUE THREAD

**Issue by gualse** [bouncepaw/mycorrhiza#134]
I think a hash in recent changes should be link to full diff page. The page should have url `/primitive-diff/<hash>` but now this url doesn't work without hypha after hash, it reset connection or return `502 Bad Gateway` if you use nginx.

**Comment by bouncepaw** [comment]
What is a full diff page? Please describe what is there

**Comment by gualse** [comment]
@bouncepaw ordinary primary diff but for full commit instead for one hypha

**Comment by bouncepaw** [comment]
How does it work for changes to non-text files? Does it link anything else?

**Comment by gualse** [comment]
@bouncepaw doesn't matter yet. I think we should just create link to current primary diff and fix diff for work without hypha first.

**Comment by bouncepaw** [comment]
What you mean ‘doesn't matter yet’? Do you want to simply ignore non-text files? That sounds ok.

I don't understand the second sentence. Also, it is primitive diff, not primary diff.

**Comment by gualse** [comment]
I don't want us to touch diff itself yet. I just want us to create link to it and fix 502. After fix, we might think about diff update, but not now. And yes, I mean "primitive diff", "primary diff" is typo.

**Comment by bouncepaw** [comment]
What do you mean fix 502?, it's not an error.

You want this:
* On `/recent-changes/`, you want the hashes link to `/primitive-diff/<hash>`.
* `/primitive-diff/<hash>` is different from `/primitive-diff/<hash>/<hypha>`.
* `/primitive-diff/<hash>` is a concatenation of all valid `/primitive-diff/<hash>/<hypha>`.
* The whole diffing stuff should be reworked later.

Did I get you right? Seems good to me.

**Comment by gualse** [comment]
> it reset connection or return 502 Bad Gateway if you use nginx.

For example:
https://mycorrhiza.wiki/primitive-diff/HEAD..HEAD~40/mycomarkup is diff for mycomarkup hypha.
https://mycorrhiza.wiki/primitive-diff/HEAD..HEAD~40/mycorrhiza_wiki is diff for mycorrhiza_wiki hypha
https://mycorrhiza.wiki/primitive-diff/HEAD..HEAD~40 is looking like full diff but it doesn't work and return 502 for every diff.

**Comment by gualse** [comment]
@bouncepaw `/primitive-diff/<hash>` should be the same as `/primitive-diff/<hash>/<hypha>` but for full commit.

**Comment by bouncepaw** [comment]
The fact that first two links show something is a bug, actually. Only hashes are meant to go there. The third shows nothing, yeah, that's how it's made.

> /primitive-diff/<hash> should be the same as /primitive-diff/<hash>/<hypha> but for full commit.

This is conceptually impossible and makes no sense, commits can change multiple hyphae, and they often do.

**Comment by gualse** [comment]
> The fact that first two links show something is a bug, actually.

Errr… isn't it feature? Okay… (but I don't think you should fix it)

> conceptually impossible

You didn't understand me. I mean `/primitive-diff/<hash>` should show change for current commit but for all hyphae that commit has.

**Comment by bouncepaw** [comment]
> Errr… isn't it feature?

It's not. I'm thrilled by your creativity though. I'll leave it be for now, but won't hesitate to accept a fix from someone else.

> You didn't understand me. I mean /primitive-diff/<hash> should show change for current commit but for all hyphae that commit has.

So it's not ‘/primitive-diff/<hash> should be the same as /primitive-diff/<hash>/<hypha> but for full commit’, but rather ‘/primitive-diff/<hash> is a concatenation of all valid /primitive-diff/<hash>/<hypha>’; I understood you correctly the first time.

Anyway, got you. The feature is a good one. One day we'll have it.

**Comment by gualse** [comment]
Okay, thanks :+1:

**Comment by bouncepaw** [comment]
Danila came up with a simple solution in the end: linking all the primitive diff pages. See #215 for the merged solution.
