### ISSUE TITLE
add --help, --version flags

### ISSUE THREAD

**Issue by DanInSpace104** [bouncepaw/mycorrhiza#147]
i know, i can see mycorrhiza version on /about page, but in situations when i haven't any wiki yet, or i am already in my terminal, trying to figure out, should i update wiki or not, such flags as --version or --help would be nice to have. Also, most of CLI-based software (or even GUI-oriented) have that flags.

**Comment by bouncepaw** [comment]
What would --help show?

**Comment by DanInSpace104** [comment]
> What would --help show?

how to start wiki, how to use flags, how to create new wiki, links to documentation

**Comment by bouncepaw** [comment]
I believe the man file has all that, isn't that enough?
