### ISSUE TITLE
Redirection hyphae

### ISSUE THREAD

**Issue by barskykd** [bouncepaw/mycorrhiza#152]
Idea as follows: 

* Add checkbox "Leave link behind" to "rename hypha" window
* Replace former hypha's content with link to new one (instead of deleting it)

**Comment by bouncepaw** [comment]
Thank you, this is a good idea that would work for many cases.

Questions:
* Is it on or off by default?
* Is there _just_ link in the former hypha? Or some text too? What language?

**Comment by bouncepaw** [comment]
I think such redirection hyphae should have either such content:

```
=> new hypha name | → New Hypha Name
```

Or:

```
=> new hypha name | ➡️ New Hypha Name
```

Or:

```
=>  new hypha name | 👁 New Hypha Name
```

, where eye stands for see in all languages.

**Comment by bouncepaw** [comment]
Redirection hyphae should also be added to a category for redirection hyphae. Its default name would be _redirection_.
