### ISSUE TITLE
'Link' tag of RSS is localhost

### ISSUE THREAD

**Issue by danilax86** [bouncepaw/mycorrhiza#153]
![image](https://user-images.githubusercontent.com/46713109/174915592-98078d72-de33-41ef-8a1c-9ab33c234c85.png)

**Comment by bouncepaw** [comment]
How did you configure your wiki? You need to set `Network.URL` to something

**Comment by danilax86** [comment]
Domain name is provided
<img width="566" alt="image" src="https://user-images.githubusercontent.com/46713109/174980343-aae500be-1cb2-40c4-847a-9f8ec0be6a36.png">

The same thing happens with melanocarpa too.
<img width="525" alt="image" src="https://user-images.githubusercontent.com/46713109/174980761-965b910b-611e-4ca0-8f47-f269c9911486.png">

**Comment by bouncepaw** [comment]
It's a bug then. I'll investigate
