### ISSUE TITLE
Idea of a sentences separation

### ISSUE THREAD

**Issue by danilax86** [bouncepaw/mycorrhiza#154]
I think that

input:
```
one line
one line

another line
``` 

out: 
```
one line one line
another line
```

is better than we have now
out:
``` 
one line
one line

another line
```

It is a pain not to separate sentences with lines if you write in some text editors. 
Reading the whole stuff from one edge of the screen to another is kinda exhausting

I mean 
<img width="822" alt="image" src="https://user-images.githubusercontent.com/46713109/176996345-09cdc7c2-bb69-44b1-91c2-9d5925ce14c6.png">
is better than 
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/46713109/176996357-6bae5c87-020a-4e88-863c-60b7ffb8e62d.png">
and they should be rendered the same way

You can read https://sive.rs/1s for a better understanding.

**Comment by bouncepaw** [comment]
Wontfix. Line breaks be line breaks. Configure your text editor to softwrap on a given column.

I believe we had the proposed line behaviour before. It wasn't good.

I could consider a trailing backslash to join lines though.

**Comment by danilax86** [comment]
@bouncepaw One more thing to consider. When you edit a single (or more) word in a one-line text, the diff output is insane and shows you the whole text, not your edit. So, if there is a merge conflict it is impossible to solve it, because it is a one line. Since the mycorrhiza is built upon a git, there is no other way to work, but with separate lines.

If you disagree, read this: https://grishaev.me/strings-80/
(translated by robot) 
> Next - conflicts. If the paragraph is not cut into lines of 80 characters, it is impossible to correct conflicts. Please read this sentence again: it is impossible to correct conflicts. Without cutting, a paragraph is a single line, and if Vasya corrected the letter at the beginning, and Petya at the end, it's a conflict. Write claims to the creators of Git, CSV and other version control systems. Their working unit is a string, and others are not foreseen.

**Comment by bouncepaw** [comment]
> the diff output is insane and shows you the whole text, not your edit

This is true. The proper solution is to have a better diff output though. The real solution is to ditch Git, but this is my power fantasy, it won't happen any time soon.

>  if there is a merge conflict it is impossible to solve it, because it is a one line

Merge conflicts are impossible to solve in Mycorrhiza already...
