### ISSUE TITLE
Documenting translation approaches

### ISSUE THREAD

**Issue by decentral1se** [bouncepaw/mycorrhiza#166]
How do you do multilingual pages? Is it already supported?

**Comment by bouncepaw** [comment]
If the names of the articles are sufficiently different in different languages, you can name them differently, like Apple and Pomme.

**Comment by decentral1se** [comment]
Thank you, will give it a look :100:

**Comment by decentral1se** [comment]
Apologies for so much noise but I'd like to re-open this one with a request: if I have `foo` & `foo/french` then indeed I get this lovely sub-hypha button at the bottom. However, and here is the problem, the button is at the bottom, not the top! Most people who don't speak (say, english, as default) will probably leave the page without knowing that at the very bottom of the page, there is a button to the french translation. Of course, I can add this myself but it would also be nice to perhaps signal somehow that a sub-hpyha is a language translation page so that is appears at the top?

**Comment by bouncepaw** [comment]
How does the engine know that a specific subhypha is a translation?

**Comment by decentral1se** [comment]
I'm not sure of the internals... maybe (mis-)using hypha is not the correct approach? Feel free to close. I would document the current translation work-around in https://github.com/bouncepaw/mycorrhiza/issues/166#issuecomment-1224052449 though to save work telling the next person? I would say that figuring out some sort of engine support for this would be ideal and flag "first class" translation support in mycorrhiza.

**Comment by bouncepaw** [comment]
I don't see why document it in the engine, different approaches fit different wikis. Some would translate titles, some would have sub-hyphae, some would have separate wikis.

An overview of different organization of translations would make a good article on https://mycorrhiza.wiki though!

I don't like the idea of first class translations.
