### ISSUE TITLE
Anonymous edits with moderation?

### ISSUE THREAD

**Issue by decentral1se** [bouncepaw/mycorrhiza#167]
Have a bit of a special use case I was wondering if mycorrhiza could handle:

- allow anonymous edits (from people with no accounts)
- have these edits "pending" until a moderator approves them

If you have some work-around or existing way of supporting it, i'd love to hear it.

**Comment by bouncepaw** [comment]
Something like this is planned, but is not currently being implemented. I don't know of any workarounds.

**Comment by decentral1se** [comment]
Cool! If you need testers or anyone to bounce the idea off, please let me know :+1:

**Comment by bouncepaw** [comment]
Sorry, closed accidentally
