### ISSUE TITLE
Publish container image for mycorrhiza?

### ISSUE THREAD

**Issue by decentral1se** [bouncepaw/mycorrhiza#168]
Loving the statically compiled binaries but for projects like https://coopcloud.tech who can only serve containers, it would be very handy to get an image published from upstream. If you're not against it, I could submit the pull request myself. I am aiming to make a Co-op Cloud recipe so this would help me :smile: You'd have to integrate yourselves into docker hub somehow though (it can also be done manually, e.g. `docker build ...` & `docker push ...`) to get the `bouncepaw/...` namespace.

**Comment by bouncepaw** [comment]
We generally delegate Mycorrhiza packaging on other platforms. We have packages on AUR and Alpine which are maintained separately, and it works great. We want the same for Docker thingy and that Coop cloud thingy. So, if you want to do this yourself, we will be glad! We will add links to the deployment guide on the wiki:

=> https://mycorrhiza.wiki/hypha/deployment

We have a Dockerfile though. It was contributed and we just kept it. We actually have no idea how to use Docker.

**Comment by decentral1se** [comment]
Fair enough! I've done some publishing/packaging, here are the links (WIP...):

- https://hub.docker.com/r/thecoopcloud/mycorrhiza
- https://git.coopcloud.tech/coop-cloud/mycorrhiza
