### ISSUE TITLE
Possible to customise css?

### ISSUE THREAD

**Issue by decentral1se** [bouncepaw/mycorrhiza#170]
Some sort of override in `/wiki/static/` or? Couldn't find anything documented...

**Comment by handlerug** [comment]
https://mycorrhiza.wiki/hypha/file_structure:

> `static/custom.css` is sent to the user after the Common style. 

But this is impossible to find, yeah. So maybe @bouncepaw should turn this issue into a documentation issue.

**Comment by bouncepaw** [comment]
Yeah, gotta document it.
