### ISSUE TITLE
How to add multiple images in the markup?

### ISSUE THREAD

**Issue by the-digital-anarchist** [bouncepaw/mycorrhiza#173]
Cool wiki.

I've got a question, how do I add multiple images (or other media) in the markup?

For now it seems like you only can upload one media item for one page and then it sticks it add the top...

I want to add multiple images in my markup with text in between, but how to do it?

Also when I upload a image to a page with media manager it uploads the image with the same name as the page, that seems pretty weird to me and also makes it impossible to use it in the markup. Shouldn't it then just name an image, with preferable a name you give it, and upload/store it with that name, so you can use it in the markup?

Update: when trying to remove the media it returns an error that there is no media to remove.

**Comment by bouncepaw** [comment]
You have a little misconception. When you upload an image, you don't add it to the page, you make a hypha which _is_ that image (and which might also have a text description).

Also, Mycorrhiza works with hyphae, not with pages. See [docs](https://mycorrhiza.wiki/help/en/hypha) also.

And when you actually want to embed other images, use this syntax:

```myco
img {
   image name
   a different image name
}
```

See [docs](https://mycorrhiza.wiki/help/en/mycomarkup#Image_gallery) also.

> Also when I upload a image to a page with media manager it uploads the image with the same name as the page, that seems pretty weird to me and also makes it impossible to use it in the markup.

It actually makes perfect sense! I think I should make a clearer indication on the media manager page, though.
