### ISSUE TITLE
No version information embedded in binaries built on macOS

### ISSUE THREAD

**Issue by handlerug** [bouncepaw/mycorrhiza#174]
The `!=` operator has appeared in GNU Make 4.0 (released in 2013), but the GNU Make version on macOS is 3.81 from 2006 (lol). This should not cause issues in the immediate future because right now Mycorrhiza is pure Go and can be cross-compiled from a proper OS, but it will cause issues once it starts linking with C libraries (such as sqlite) and you won't be able to easily compile it for any OS without a C cross-compiler anymore.

**Comment by bouncepaw** [comment]
Can confirm. This is a problem right now, actually. Is there a way to solve this without writing the version information by hand like before?
