### ISSUE TITLE
List of shortcuts appears when you are inside input text block

### ISSUE THREAD

**Issue by danilax86** [bouncepaw/mycorrhiza#178]
It is impossible to type a question mark anywhere in a text you are writing

**Comment by handlerug** [comment]
This check needs to be fixed: https://github.com/bouncepaw/mycorrhiza/blob/master/static/shortcuts.js#L57

**Comment by bouncepaw** [comment]
This is a fun bug. Looks like we'll have the 1.12.1 release.

**Comment by bouncepaw** [comment]
Fixed in 1.12.1
