### ISSUE TITLE
Is there a way to fetch the data in an hypha by json, like an api?

### ISSUE THREAD

**Issue by the-digital-anarchist** [bouncepaw/mycorrhiza#180]
I want to read the data in the hypha from an external source, is this easily doable?

**Comment by bouncepaw** [comment]
There is no API yet. You have to parse HTML for now.

An API is planned, though. What data do you want to have in this API?

**Comment by the-digital-anarchist** [comment]
Parsing the HTML would be possible but it requires some resources to read the markup.
Having the data in json would be easier to read.

I was planning to build [page preview hover cards](https://www.mediawiki.org/wiki/Page_Previews) on my own website and display sections (like the partagraph under a anchor tag) or a preview of a hypha.
So I then need a way to easily read the data from the hypha's.

side note: the whole idea if the page preview hover cards in mycorrhiza would be awesome to maybe it can be built on the same code.

**Comment by handlerug** [comment]
You *can* fetch the source markup at `/text/<name>`, but that would be the raw mycomarkup.

**Comment by bouncepaw** [comment]
I'll close this for now, but it doesn't mean there won't be any API in the future.
