### ISSUE TITLE
Working in subpath?

### ISSUE THREAD

**Issue by ManjTi** [bouncepaw/mycorrhiza#190]
I wonder if it's possible to make wiki work at domain subpath like /wiki
If not, I think it will be a useful feature.

**Comment by bouncepaw** [comment]
It is not yet possible.

More people requested it. Can you tell me about your use case, why do you need that?

**Comment by decentral1se** [comment]
Oh yeh, need this too. Use case: pubnix / shared server environment where you have `~/public_html` sharing from your home directory and no access to the root of the domain or Nginx configuration as adminstrator. I've just tried this and the software assumes it controls the root of the domain.

**Comment by bouncepaw** [comment]
> Use case: pubnix / shared server environment where you have `~/public_html` sharing from your home directory

How is it related? Mycorrhiza wikis can be stored in any directory.

**Comment by decentral1se** [comment]
Nginx will typically serve `pubnix.com/~foo` but when you load the page, the software assumes `pubnix.com/static/` holds the CSS but instead, `pubnix.com/~foo/static` holds the static files (so you get 404'd styles). Also some of the URLs e.g. registration assume `pubnix.com/...` without the sub-path which breaks ofc.

**Comment by bouncepaw** [comment]
> Nginx will typically serve `pubnix.com/~foo` but when you load the page, the software assumes `pubnix.com/static/` holds the CSS but instead, `pubnix.com/~foo/static` holds the static files (so you get 404'd styles). Also some of the URLs e.g. registration assume `pubnix.com/...` without the sub-path which breaks ofc.

You seem to use filesystem paths and URLs interchangeably. They are different. I don't quite understand what do you mean. Can you please provide a complete list of actions, what did you expect, and what happened instead.

**Comment by decentral1se** [comment]
> You seem to use filesystem paths and URLs interchangeably.

I only used URLs.

**Comment by shivrm** [comment]
> Note for a future implementer. The `<base>` tag can be used:

I tried adding the `<base>` tag, but it doesn't work. Root-relative links (such as `/hypha/Name`) are still relative to the root of the path specified in `<base>`.

Example: (https://jsbin.com/maciqavoja)
```html
<head>
    <base href="https://github.com/shivrm/">
</head>
<a href="/mycorrhiza">/mycorrhiza</a> links to https://github.com/mycorrhiza
```

**Comment by bouncepaw** [comment]
After some time, I think it's a clear wontfix for the foreseeable future.
