### ISSUE TITLE
Image upload?

### ISSUE THREAD

**Issue by decentral1se** [bouncepaw/mycorrhiza#195]
Point to images elsewhere is fine but it'd be nice to have them stored in the wiki itself. This helps when doing a migration and for offline / local scenarios.

**Comment by bouncepaw** [comment]
You mean, not as hyphae?

**Comment by decentral1se** [comment]
Ah, right. I keep forgetting I can do that (which is maybe my brain but also potentially a UI/UX thing). Thanks, closing.
