### ISSUE TITLE
Asciidoc instead of Mycomarkup?

### ISSUE THREAD

**Issue by hhartzer** [bouncepaw/mycorrhiza#202]
Re: https://mycorrhiza.wiki/hypha/essay/why_mycomarkup

I know this is highly controversial and I'm sure there's a lot of good reasons for Mycomarkup, but it is a new format among many.

I though that Asciidoc looked similar and it features something like transclusion: https://docs.asciidoctor.org/asciidoc/latest/directives/include/

Is Asciidoc worthy of Mycorrhiza? I really don't know enough to say -- I am just curious! I'm quite happy using Mycomarkup.

**Comment by bouncepaw** [comment]
Mycomarkup is kinda too old to rip out, Mycorrhiza is like three years old or something. I have thousands of documents in Mycomarkup. No one would actually be happy about that. And worst of all, Asciidoc is a very bad choice for a wiki markup (but quite a good one for a book), as it offers many unneeded features while not offering some needed features. For example, I've never found any notion of something like a wikilink there. It has a better ordered list syntax than Mycomarkup, though.

But whatever. Not worth it. Wontfix.

**Comment by hhartzer** [comment]
I understand! Thank you for for taking the time to explain!
