### ISSUE TITLE
Creating `static/common.css` doesn't redefine default styles

### ISSUE THREAD

**Issue by shivrm** [bouncepaw/mycorrhiza#203]
The [help page on File Structure](https://mycorrhiza.wiki/help/en/file_structure) says that "`static/common.css` redefines the engine's default style, if exists.". But creating this file doesn't seem to affect the page style at all.

The source code shows that `static/default.css` contains the default style. Creating this file redefines the default style. Maybe the help page should be updated to reflect this.

**Comment by bouncepaw** [comment]
Thank you, I've updated the docs.
