### ISSUE TITLE
GPG Password Prompt when Creating Hyphae

### ISSUE THREAD

**Issue by shivrm** [bouncepaw/mycorrhiza#207]
I have set up git to sign commits using my GPG Key. Mycorrhiza uses `git commit` as well, so I get a password prompt for signing the commit whenever I create a hypha.

In my opinion, GPG signing is not appropriate here as the commits are made by an separate, anonymous user. It would be nice if [GPG signing was disabled](https://stackoverflow.com/a/48110281) when hyphae are created/updated.

**Comment by bouncepaw** [comment]
Thanks for reporting, I'll look into it. Seems like an easy fix.

**Comment by bouncepaw** [comment]
Added the `--no-gpg-sign` to `git commit` invocation, the problem should be gone. Please tell if you run into any other problems with that.
