### ISSUE TITLE
`silentGitsh` ignores environment variables

### ISSUE THREAD

**Issue by shivrm** [bouncepaw/mycorrhiza#209]
[`silentGitsh`](https://github.com/bouncepaw/mycorrhiza/blob/master/history/history.go#L69) passes only `gitEnv` when calling commands, whereas normal `gitsh` passes both system environment variables and `gitEnv`. The comments say that "silentGitsh is like gitsh, except it writes less to the stdout.", so I'm not sure if this is intentional behaviour.

I was running Mycorrhiza on an old device and it was crashing whenever I opened the 'Recent Changes' page. Changing this one line fixed the problem.

**Comment by bouncepaw** [comment]
Well, I intended them to be the same, except for the output. Thanks for reporting, I'll look into that.
