### ISSUE TITLE
Changing passwords

### ISSUE THREAD

**Issue by JacksonChen666** [bouncepaw/mycorrhiza#211]
Seems like Mycorrhiza doesn't have the feature of changing passwords, for what I know.

Can be important because the password you used has been maybe leaked or something like that (accidentally pasted in wrong place).

(Would it be fine if I sent a patch (if I made one) on sourcehut even though I sent an issue on GitHub?)

Patch: https://lists.sr.ht/~bouncepaw/mycorrhiza-devel/patches/47102

**Comment by bouncepaw** [comment]
Sounds good.

Patches are totally fine.

**Comment by bouncepaw** [comment]
Administrators can change users' groups and delete them at /admin/users. Does that count as user account management?

Following the standard sounds good.

**Comment by bouncepaw** [comment]
> What if a user wants to change the password themselves? Or delete their account themselves?

They would need a separate page for that.

> What URL path should be used for the user changing their password for themselves?

`/change-password` or something. Maybe `/settings/change-password`, I want to have a `/settings` page one day.

**Comment by bouncepaw** [comment]
Restrict to local, yes. Telegram users have empty passwords, their authentication is done through Telegram.
