### ISSUE TITLE
Mycorrhiza 1.15

### ISSUE THREAD

**Issue by bouncepaw** [bouncepaw/mycorrhiza#216]
It's about time. I hope I'll do it before the summer ends.

Absolutely required for the release:

* [x] #205
* [x] Fix JSON feeds
* [x] #218
* [x] #226

Very nice to have:

* [x] #220
* [x] #230
* [x] #231
* [x] #237

----

I changed my mind and do not want to include the following items in this release, but keeping here for history:

* Windows shenanigans
   * [x] #86
   * [x] Support weird Windows paths
   * Maybe postponed, see below.
* [x] #213
* [x] #229
* [x] ~~#124~~
   * Use Rosie's unfinished patch as a base?

**Comment by bouncepaw** [comment]
I'm thinking about not fixing those Windows issues for now. It's unpleasant to test them. I mean, they just drive me crazy. And the FS-related code is a mess, just checked it out. I can always get to these problems later...

**Comment by bouncepaw** [comment]
Come to think of it, #124 should probably be made after all views are migrated to the new template system (the refactoring is underway on `newtmpl` branch) to avoid extra work. So, removing from the list.

**Comment by bouncepaw** [comment]
Just to release it already, I removed most of the plans for the release. We'll get to that later. Only one item remaining, and it's simple.

**Comment by bouncepaw** [comment]
Mycorrhiza 1.15 is released: https://github.com/bouncepaw/mycorrhiza/releases/tag/v1.15.0

PR work:

* [ ] Wiki
* [ ] Telegram
* [ ] Fediverse

**Comment by bouncepaw** [comment]
All done! Closing.

**Comment by hhartzer** [comment]
Awesome! Thank you so much, @bouncepaw!
