### ISSUE TITLE
Categories is not available

### ISSUE THREAD

**Issue by juev** [bouncepaw/mycorrhiza#217]
Hello and thanks for the app!

I deployed an application in docker, registered one user, and disabled wiki registration. Now I can create and edit pages under authorization. Everything seems to be fine. But I don't see anywhere where I can include the page in a new category.

I don't have the ability to create new categories or include pages in them. And in the list of categories, I have an empty list displayed.

What could be the problem? What am I doing wrong?

**Comment by bouncepaw** [comment]
<img width="1392" alt="Снимок экрана 2024-04-07 в 11 35 11" src="https://github.com/bouncepaw/mycorrhiza/assets/22562024/094b4113-6bce-47f0-a8d6-fce87e8aa828">

Can you find this? Depending on the screen size, this thing might be in a different place, but it is always there for logged in users. Enter the name of the category you want to add the hypha in and press Enter or the plus button near the input field. If the category does not exist, it will be created for you.

**Comment by juev** [comment]
It's strange, but I don't see such a section on my pages.

<img width="1728" alt="wiki" src="https://github.com/bouncepaw/mycorrhiza/assets/114635/dc624e07-0c8d-43e6-bc19-e5ef828925df">

**Comment by bouncepaw** [comment]
Take a look at the `users.json` file. I suppose your user has `editor` group, for editing categories you would need at least `trusted`. I recommend you setting it to `admin`. You were actually supposed to create the first user with `-create-admin` CLI option, I guess I should make it more clear.

**Comment by juev** [comment]
Now everything is working, thanks!
I changed the group from editor to admin and the categories appeared. Great, thanks!

**Comment by bouncepaw** [comment]
Great!

P.S. I've taken a look at your wiki and website. You seem like a heavy bookmark collector! You might like [Betula](https://betula.mycorrhiza.wiki), a project related to Mycorrhiza, that was made specifically to collect many bookmarks. See [my instance](https://links.bouncepaw.com) for an example.

**Comment by juev** [comment]
Thanks!

Yes, I have a separate website with links. links.evsyukov.org
Another one with github actions: https://github.com/juev/links

I use linkding for his work. I don't like the fact that it is written in php and requires more memory. But it has a number of features that I like:

- creating an archived copy using web archive
- creating an archived copy of the page on a local disk
- search by bookmarks, tags and description

Betula is a very interesting project, I have already looked at it. But I'm not ready to migrate yet.

I also created docker-compose files for your projects. And I use them to run on my Synology NAS:

https://github.com/juev/docker-compose

I tried to get rid of the git dependency in mycorrhiza. So far, without success. As a result, the alpine image is used in the same way as in your example.

**Comment by bouncepaw** [comment]
Yeah, archived copies are wonderful, I want to have this too one day. links.evsyukov.org is not viewable without auth, by the way, is this intended?

Getting rid of Git is basically pointless, in my opinion. But it's possible. You have to pass a fake git in `$PATH`:

https://mycorrhiza.wiki/hypha/using_without_git

A script like this might do:
```sh
#!/bin/sh
case "$1" in
	add|commit|init|config)
		exit 0
		;;
	*)
		exit 1
		;;
esac
```

**Comment by juev** [comment]
> links.evsyukov.org is not viewable without auth, by the way, is this intended?

I have several thousand saved links. Some of which are very personal. I wouldn't want anyone to see them. Going through all the links just to open them to others? I decided it was easier to keep it under lock and key.
