### ISSUE TITLE
Make -create-admin more known

### ISSUE THREAD

**Issue by bouncepaw** [bouncepaw/mycorrhiza#218]
Judging by #217 I conclude that not many people know about this option. Maybe they should all know? I want to make it more noticeable somehow.

**Comment by juev** [comment]
In my opinion, creating an admin using a command line argument is very non-trivial and incomprehensible.

Again, just giving an opinion. When creating a default user, assign the first user admin rights. And he can control further, who else can enter which groups.

Thus, it will be enough to launch a wiki, create a user, and that will be enough.

Do we have options when, with authorization, there may be cases when admin rights are not needed? In my opinion, this is impossible. At least one user must be an admin.
