### ISSUE TITLE
custom.css file

### ISSUE THREAD

**Issue by juev** [bouncepaw/mycorrhiza#221]
Hi.

I tried to make changes to the wiki styles today. I changed the `static/custom.css` file, after which I even restarted docker container. But I don't see any changes in the style file being used.

What could be the problem?

**Comment by bouncepaw** [comment]
Perhaps it's the browser cache?

**Comment by juev** [comment]
Oh, you're probably right. Since I checked through curl, there are these changes in the styles.

The browser still believes that the file has not changed, and as a result does not update the cache. wiki does not have support for an E-Tag tag to indicate file updates?

**Comment by bouncepaw** [comment]
I think it doesn't have E-Tags, I don't know what they are.

**Comment by juev** [comment]
Description link: [HTTP_ETag](https://ru.wikipedia.org/wiki/HTTP_ETag )

As another solution, this is changing the file name for styles, and possibly for all static resources, such as styles or scripts, to names containing a hash of the file contents.

It was:
```
<link rel="stylesheet" href="/static/style.css">
```

It became:
``
<link rel="stylesheet" href="/static/style-d587bbd6e38337f5accd.css">
``

Thus, when updating the contents of the file, we will receive new file names that are missing from the cache. This will allow static resources to be cached for a long time, but at the same time have up-to-date data at the front.

What do you think?

**Comment by bouncepaw** [comment]
Changing filenames looks dirty, I don't like it.

ETags seem good, I'd be glad to have them, and not just for stylesheets, but for all stuff. I get the feeling that it won't be that easy to implement it, given current chaotic Mycorrhiza codebase...

Just to be clear, I won't be implementing them any time soon, but will gladly accept a good PR. Open a new issue, maybe?
