### ISSUE TITLE
Can't remove media file from hypha

### ISSUE THREAD

**Issue by locrianz** [bouncepaw/mycorrhiza#233]
I tried uploading a media file (an mp3) to test it out, but I can't remove it now.

I click on "manage media" and then click the "remove media" button, and I get this error:

```
Could not unattach this hypha due to internal server errors: [exit status 128 exit status 128]
```

I can't delete the hypha, either; I get this error:

```
exit status 128
```

**Comment by bouncepaw** [comment]
What was the name of the hypha? Are you running Windows?

**Comment by locrianz** [comment]
The hypha was "Home" (I clicked to add the media without realizing it would be attached to the hypha I was already on, though it makes sense in retrospect), and no, I'm on Ubuntu.

I wound up nuking the install and starting over since it was literally the first thing I'd done.

**Comment by bouncepaw** [comment]
Yeah, Home is the killer name. There is a bug related to it, which is fixed in the development version now. Your wiki probably lies in `/home/locrianz`, so be careful with hyphae named Home, Locrianz, Locri and whatnot until the next version is out, renaming is expected to misbehave too.

**Comment by locrianz** [comment]
Got it, thanks for the help!
