### ISSUE TITLE
Decrease tab-size

### ISSUE THREAD

**Issue by danilax86** [bouncepaw/mycorrhiza#237]
In code blocks a tab character adds too much indentation, but it is possible to make code blocks more compact by decreasing CSS `tab-size` property.

**Comment by bouncepaw** [comment]
What tab-size should we use? 2, 3 or 4 characters? I know that 3 is a weird choice, but it's so cute and clumsy!! Almost as compact as 2, almost as acute as 4. Golden indentation.
