### ISSUE TITLE
No line wrap for `<pre>`

### ISSUE THREAD

**Issue by kovmir** [bouncepaw/mycorrhiza#256]
`<pre>` snippets between tripple backticks should have a horizontal scroll bar and no line wrap, as they are often meant to be copied just as they are.

**Comment by bouncepaw** [comment]
Hello! This is a duplicate of https://github.com/bouncepaw/mycorrhiza/issues/183

TL;DR: won't fix; use `custom.css` to redefine this style.

**Comment by kovmir** [comment]
My apologies... Thank you for a quick reply.
