### ISSUE TITLE
mycomarcup cheatsheet below edit textarea

### ISSUE THREAD

**Issue by DanInSpace104** [bouncepaw/mycorrhiza#42]
I often needs to open cheatsheet in different tab to write new things. It'll be super useful to have most used markup things under textarea on the edit page

**Comment by bouncepaw** [comment]
In 1.1, there is a nice toolbar and a link to the manual. Do we really need a cheatsheet now?

**Comment by DanInSpace104** [comment]
@bouncepaw With such useful toolbar, i don't think we need cheatsheet anymore :)
