### ISSUE TITLE
New folder structure

### ISSUE THREAD

**Issue by bouncepaw** [bouncepaw/mycorrhiza#57]
See #56 for the beginning of the conversation.

----

I suppose we do need such folder structure. In fact, I've done something like that for Cyberrachel already.

Also, it is easier to have a unique copy of Mycorrhiza for each wiki you have.

**Comment by bouncepaw** [comment]
> It's a foundation for supporting different storages.
That's where [dynamic hyphae](https://mycorrhiza.lesarbr.es/hypha/idea/dynamic_hyphae) will be stored, cool. `wiki.dynamic` or something.

> Why is this bad?
The only downside is that it's a breaking change. Good news: full compatibility between versions was never really promised!

So, what do others think?

**Comment by bouncepaw** [comment]
> maybe mycorrhiza can use sqlite db for cache (tokens, pre-renders etc)

It can and it may happen like that one day. Not anytime soon though...

**Comment by bouncepaw** [comment]
I've written https://github.com/bouncepaw/mycorrhiza/blob/f61a4c1168375a364834c5c4644bfc9655a94277/files/Structure.md for developers' pleasure

**Comment by handlerug** [comment]
cool

**Comment by DanInSpace104** [comment]
@bouncepaw cool ideas, i just want to remind about plugins that can be changed without recompiling and that can depend on wiki. Such as js-only plugins

**Comment by bouncepaw** [comment]
Implemented in 1.2
