### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by bouncepaw** [bouncepaw/mycorrhiza#64]
Most of Mycorrhiza users have an unhealthy tendency to keyboards and everything related to them. I keep wondering why is that a case.

Nevertheless, it seems like some sort of keyboard shortcut support is needed.

## Cons
* One can already Tab around. It has been tested, it works.
* One can use a keyboard-centric navigation assistance tool such as VoiceOver.
* One can install a special browser or an extension with vim-like browser navigation.

All of these three statements undermine the need for a shortcut system. Not like I care.

## Pros
Are obvious.

## Way 1. Access keys
It turned out there is a feature called *Access keys* built in browsers. Hotkeys without JavaScript, how cool is that!

I tried to find some recommendations or standards on the topic. An initiative called “Standard access keys” was made a long time ago. Nowadays, their site is dead. We can access it through Web Archive:

=> [Standard access keys](https://web.archive.org/web/20210323165914/https://www.standardaccesskeys.com/SAK2014/)

You can read it, it's not too long.

I found it unsatisfactory. Here's what I'm thinking of:

* Numbers 1 to 9 to access the header links. 0 accesses your page or the login page.
* Letters v(iew hypha), e(dit), a(ttachment), h(istory), r(ename), d(elete) access the correspinding tabs.

The biggest problem with access keys is that they require modifiers. And they are different not only between OSes but between browsers too.

We don't have much design space and can only fit so much functions.

But no JS! Unless...

## Way 2. JavaScript
Oh no! Our archnemesis! The nightmare brought alive!

The tool bar turned out to be nice. Let's have more JS.

Let's just drop modifier keys for most cases.

The letters mentioned above access the tabs. No modifiers.

Letters n and p navigate to next and previous hypha. Letter s navigates to superhypha, if there is one. Or maybe Ctrl+arrows? Gotta think about that.

Letter g is used like a prefix for go-to command: gh home hypha, gu user hypha, gl hypha list, gr recent changes... Numbers can be used to access the entries in the top bar. Note that with the default top bar some entries have two shortcuts: gh and g1 for home hypha, for example.

In the editor, Ctrl-Enter saves the hypha. Also, shortcuts similar to rich text editors could be made: Ctrl+B for bold, for example. This list requires more research so let's think of it later.

Now, cool time. Numbers 1 to 9 access the first nine links in the hypha on the screen! Not enough for you? Grab your most then, why do you have it then?

----

As you can guess, I like the second approach more. List your ideas in this issue.

This feature is not planned for the 1.2 release.

**Comment by DanInSpace104** [comment]
@bouncepaw I think if you turned off js or use cli-browser, you already use keyboard and shortcuts. So js is completely fine for that purpose. But where to put help panel? On "?" key, like in vimium etc?

**Comment by handlerug** [comment]
> But where to put help panel? On "?" key, like in vimium etc?

`Shift+/`, which'll result in a `?` key press event, yes. Already working on it btw

**Comment by GuAlSe** [comment]
@bouncepaw My friend once told me: "Any feature with the ability to disable is useful". I think we should make disable switch.
Also I think we should use JS and arrows keys:
Left — previous hypha
Right — next hypha
Up — parent hypha
Down — first child hypha.
Ctrl+Enter open edit page, but on edit page itself save hypha text.
I also think we can create customizable shortcuts.
JS isn't bad until it's optional.

**Comment by bouncepaw** [comment]
@GuAlSe What kind of disable switch? Per user or per wiki? Whatever the case, I think we don't need that switch. Configurability is not always desired. Users with such unusual demands already know a way to disable it, wiki administrators can override any script without any switch (thanks to one of the latest @handlerug's commits).

Also, using *just* arrows for hypha navigation is not good because it overrides the default browser behavior. Doing so is harmful. What about using them together with alt? Hmm...

Any JS is optional, one can just turn it off in the browser settings.

**Comment by GuAlSe** [comment]
@bouncepaw Per user of course. I use addon for vim shortcuts and I afraid that Mycorrhiza will config with it.
Alt+Arrows sounds good.

**Comment by bouncepaw** [comment]
@GuAlSe There is no such problem. Vim shortcuts intercept all keystrokes, so Mycorrhiza does not receive any. No conflict

**Comment by handlerug** [comment]
Shipping in 1.2 it seems 👀
