### ISSUE TITLE
Tree navigation

### ISSUE THREAD

**Issue by bouncepaw** [bouncepaw/mycorrhiza#7]
One of the killer features of MycorrhizaWiki is intended to be the so-called *tree navigation*.

1. At the most basic level, users should have links to all direct ancestors (for hypha `Fungi/Amanita/Muscaria` that would be hyphae `Fungi` and `Fungi/Amanita`) and to the direct children. It's also possible to show children of children recursively.
1. If we choose to go more advanced, we can also show siblings of a hypha (for the aformentioned hypha that would be, for example, `Fungi/Amanita/Gemmata` and `Fungi/Amanita/Regalis`).
1. If we choose to go the most advanced, we can show _whole wiki tree_.

So, what should we choose? I like the second option most of all as it has the highest power-to-weight ratio. I'll start implementing it soon, but perhaps the third one is better. Discuss.

**Comment by DanInSpace104** [comment]
We can use second option in navigation bar, and create dedicated page with whole wiki tree

**Comment by bouncepaw** [comment]
The second option has been implemented but it's not perfect now. Some hyphae can be omitted :-( A dedicated page with the whole wiki tree may be done someday. I'm keeping this issue open until the tree algorithm is improved to not omit those hyphae.

**Comment by bouncepaw** [comment]
Thinking about making the tree branches collapsible using the `<details>` tag. They will still be opened by default.

**Comment by bouncepaw** [comment]
Thinking about showing sister hyphae in a sidebar. See [this design proposal](https://www.figma.com/file/1zWTC4Kf7Ql8IoDuIukfF2/Klavarog.tk) by isuo. What about child hyphae? Showing them below? In a different sidebar?

**Comment by bouncepaw** [comment]
Since 0.13, relative hyphae are shown in the right sidebar, if there is space for them.

Only one thing is left unsolved: collapsing the tree!

**Comment by bouncepaw** [comment]
Since 0.13, subhyphae are shown below the current hypha. The whole idea of a collapsible tree is no longer applicable, therefore the issue is solved.
