### ISSUE TITLE
Built-in documentation

### ISSUE THREAD

**Issue by bouncepaw** [bouncepaw/mycorrhiza#79]
It's nice to have it.

Here are the topics:
* [x] Hypha
* [x] Attachment
* [x] Mycomarkup
* [x] New features of 1.3
* [ ] Configuration help (for administrators)
* [ ] Other quirks

Edit the list above to add an entry to do or mark as done.

I'm making this issue to add the Documentation label that I so long for.

**Comment by bouncepaw** [comment]
We have a Russian translation of the docs! Sadly, there is a problem with terminology. We address that in #116

**Comment by bouncepaw** [comment]
I feel a strong urge to delete the Russian translation of the docs, because:

* It is expired, because:
  * The one who writes the English docs (me) does not want to and does not plan to translate them.
  * There is no person who would translate them in time.
* It is incomplete (even more than the original docs!) for similar reasons.

If no Russian translation maintainer shows up in December or in the beginning of January, I will delete the translation.

🏝

**Comment by DanInSpace104** [comment]
> If no Russian translation maintainer shows up in December or in the beginning of January, I will delete the translation.

I can help with that

**Comment by bouncepaw** [comment]
> > If no Russian translation maintainer shows up in December or in the beginning of January, I will delete the translation.
>
> I can help with that

Please help.

**Comment by bouncepaw** [comment]
The Russian documentation has been deleted in 2ac18748820ea2155c3791a0548357fa45248ba2

**Comment by DanInSpace104** [comment]
@bouncepaw

**Comment by bouncepaw** [comment]
There is no point in having this issue open, as it is evergreen: documentation can always be improved. Closing
