### ISSUE TITLE
Search improvements

### ISSUE THREAD

**Issue by kseistrup** [bouncepaw/mycorrhiza#80]
As of commit ae03dbcd64eca394bec1a5f5a39f27e929cf4df7 I see the following when using the search box in Mycorrhiza:

1. Seaches seem to be case-sensitive.
2. A search with zero hits leads you to a 404 page, and you have to use the browser's back-button in order to return to the wiki.

It would be nice to have case-insensitive search so that you needn't remember the case of the title of all pages.

It would also be nice if a null-result lets you stay in the wiki and tells you that your search has no hits.

**Comment by handlerug** [comment]
Thanks for the report! I think I'm the one who introduced the second bug; I'll fix it today later.

**Comment by bouncepaw** [comment]
I updated the engine to the specified commit on https://mycorrhiza.wiki and here's what I can say.

1. Search is case-insensitive, compare results of https://mycorrhiza.wiki/title-search/?q=Essay and https://mycorrhiza.wiki/title-search/?q=essay
2. It does not, see https://mycorrhiza.wiki/title-search/?q=owl

The only bug I found is that the search bar does not work (it would send you to https://mycorrhiza.wiki/title-search?q=kek instead of https://mycorrhiza.wiki/title-search/?q=kek (and both should work, actually)). I guess @handlerug will fix that.

**Comment by kseistrup** [comment]
I don't know what to say. My wiki has exactly 3 pages: DNS, Syphon, and kas. If I use the title-search field to search for “Syphon” I am shown the page. If I use the title-search field to search for “syphon” I am sent to a 404 page. The former will send me to `/title-search/?q=Syphon`, the latter will send me to `/title-search?q=syphon`. Perhaps I'm just hit by the bug you're mentioning, but I don't understand why one will send me somewhere and the other elsewhere.

Perhaps we best wait the for bugfix…

**Comment by handlerug** [comment]
Should be fixed in https://github.com/bouncepaw/mycorrhiza/commit/eb22cf206cb11a31e420464dd2782aa58961082a

**Comment by bouncepaw** [comment]
Works fine for me.

One more thing. Should we show something like _your search returned nothing_ or keep it the current way?

**Comment by handlerug** [comment]
It probably should (_that whole title search thing is a big hack anyway..._)

**Comment by kseistrup** [comment]
Could it be because I am running Mycorrhiza behind a reverse proxy that I am seeing different things?

Let me try @handlerug's fix…

**Comment by bouncepaw** [comment]
I run all my wikis through reverse proxies (`nginx`, in particular) and don't have an issue

**Comment by kseistrup** [comment]
Well, that's weird because it's very reproducible here (I am using Caddy as webserver and Firefox as browser).

But I am happy to be able to report that @handlerug's fix is giving me what I want: case-insensitive search and no 404 page.

That Mycorrhiza says that “Hyphae that have matched the query are listed below” and the list is empty is a very minor issue for me.

Thanks.

**Comment by bouncepaw** [comment]
Uh let's close this issue then
