### ISSUE TITLE
Auto publish AUR package

### ISSUE THREAD

**Issue by GuAlSe** [bouncepaw/mycorrhiza#83]
We should publish AUR package automatically use something like https://github.com/marketplace/actions/publish-aur-package-2. Also we may create mycorrhiza-git package. (This package will be updated after any commit on main branch)

**Comment by YogurtTheHorse** [comment]
@GuAlSe Еще чуть чуть и придумаете релиз ветку

**Comment by bouncepaw** [comment]
Why not. Make a pull request, I guess. It'll go to https://github.com/bouncepaw/mycorrhiza/tree/master/.github/workflows

**Comment by bouncepaw** [comment]
Here's what AUR [says](https://aur.archlinux.org/packages/?O=0&K=mycorrhiza) about Mycorrhiza packages.

There is `mycorrhiza` at version 1.7.0 maintained by @kseistrup (thanks a lot) and outdated `mycorrhiza-bin` at version 1.3.0.

Seistrup, please tell us how do you manage to maintain the package. Do you do it by hand or have you automated it somehow?

**Comment by kseistrup** [comment]
@bouncepaw 

> Do you do it by hand or have you automated it somehow?

It's all manual: Whenever I receive a notification email from Microsoft Github, I update the `PKGBUILD` file on AUR accordingly.

**Comment by bouncepaw** [comment]
@kseistrup 

Incredible! In that case, do you feel the need to automate it? If not, I'll close the issue. If yes, I'll keep the issue open.

**Comment by kseistrup** [comment]
@bouncepaw, at the current release frequency — and as long as I don't manually have to keep an eye on new releases here — I don't feel any need to automate the AUR package, no.

**Comment by bouncepaw** [comment]
Alright then
